spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: snnLab
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

singleF2FJob:
  scheduler:
    cronExpression: "*/30 * * * * *"